# Generated by generate-wrapper-unit-tests.py; do not edit.
set(P101_FAULT_SHARD_TESTS
    test_fault_wrappers_sched
    test_fault_wrappers_signal
    test_fault_wrappers_spawn
    test_fault_wrappers_stdio
    test_fault_wrappers_stdlib
    test_fault_wrappers_sys_resource
    test_fault_wrappers_sys_times
    test_fault_wrappers_sys_wait
    test_fault_wrappers_unistd
)
